// Generated by Selenium IDE
package entity;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class UntitledTest {
  private WebDriver driver;

  private Map<String, Object> vars;

  JavascriptExecutor js;

  @Before
  public void setUp() {

    /*
     * For Windows users change chromedrive to chromedriver.exe
     */
    System.setProperty("webdriver.chrome.driver", "C:\\projects\\my-project\\workspaces\\main\\Test\\chromedriver.exe");
    System.setProperty("webdriver.gecko.driver", "java/example-creator/driver/geckodriver/geckodriver");

    this.driver = new ChromeDriver();
    this.js = (JavascriptExecutor) this.driver;
    this.vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {

    this.driver.quit();
  }

  @Test
  public void untitled() {

    this.driver.get("https://www.google.de/");
    this.driver.manage().window().setSize(new Dimension(1920, 1040));
    this.driver.findElement(By.name("q")).sendKeys("hallo");
    this.driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    {
      WebElement element = this.driver.findElement(By.cssSelector(".nm6nmc"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).perform();
    }
  }
}
